# Generated by Django 4.2.5 on 2023-09-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterconfig',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='masterconfig',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.masterconfig'),
        ),
        migrations.AlterField(
            model_name='masterconfig',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='masterconfig',
            name='max_subcategory_level',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
