# Generated by Django 4.2.5 on 2023-09-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastertableconfig', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.ForeignKey(default='super_user', on_delete=django.db.models.deletion.CASCADE, related_name='account_masterconfig', to='mastertableconfig.masterconfig'),
            preserve_default=False,
        ),
    ]
