# Generated by Django 4.2.5 on 2023-09-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_masterconfig_parent_id_masterconfig_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='abc', max_length=250, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified User'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='abcd', max_length=250, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
